rules:
  - id: exam_last_minute_prep
    description: "Pre-exam nudge when an exam is imminent"
    when:
      all:
        - eq: { field: "has_exam_last_minute_prep", value: true }
        - lt: { field: "emails_sent_7d", value: 2 }
        - eq: { field: "unsubscribed", value: false }
    action:
      template_id: "exam_last_minute_prep_v1"
      priority: 100
      cooldown_days: 2

  - id: crisis_safety_hold
    description: "Suppress all nudges when crisis risk is present"
    when:
      all:
        - eq: { field: "crisis_flag", value: true }
    action:
      template_id: "safety_hold"   
      priority: 1000
      cooldown_days: 1

  - id: appointment_reminder
    description: "Nudge before a user-mentioned appointment"
    when:
      all:
        - contains_trigger: { field: "ai_email_triggers", trigger: "appointment_reminder" }
        - lt:  { field: "emails_sent_7d", value: 2 }
        - eq:  { field: "unsubscribed", value: false }
    action:
      template_id: "appointment_reminder_v1"
      priority: 91
      cooldown_days: 2



  - id: exam_post_checkin
    description: "Post-exam check-in"
    when:
      all:
        - eq: { field: "has_exam_post_checkin", value: true }
        - lt: { field: "emails_sent_7d", value: 2 }
        - eq: { field: "unsubscribed", value: false }
    action:
      template_id: "exam_post_checkin_v1"
      priority: 97
      cooldown_days: 2


  - id: exam_last_minute_prep
    description: "Pre-exam nudge when an exam is imminent (detected from AI triggers)"
    when:
      all:
        - contains_trigger: { field: "ai_email_triggers", trigger: "exam_prep" }
        - contains_trigger: { field: "ai_email_triggers", message_type: "last_minute_prep" }
        - lt:  { field: "emails_sent_7d", value: 2 }
        - eq:  { field: "unsubscribed", value: false }
    action:
      template_id: "exam_last_minute_prep_v1"
      priority: 100
      cooldown_days: 2

  - id: exam_post_checkin
    description: "Post-exam check-in (detected from AI triggers)"
    when:
      all:
        - contains_trigger: { field: "ai_email_triggers", trigger: "post_exam" }
        - contains_trigger: { field: "ai_email_triggers", message_type: "how_did_it_go" }
        - lt:  { field: "emails_sent_7d", value: 2 }
        - eq:  { field: "unsubscribed", value: false }
    action:
      template_id: "exam_post_checkin_v1"
      priority: 97
      cooldown_days: 2

  # --- ACHIEVEMENT / ENGAGEMENT ---

  - id: high_engagement_reward
    description: "Reward for highly engaged learners"
    when:
      all:
        - gte: { field: "frequency_7d", value: 100 }
        - gte: { field: "conversations_7d", value: 50 }
        - gt:  { field: "convo_sentiment_7d_avg", value: 0.5 }
        - eq:  { field: "unsubscribed", value: false }
    action:
      template_id: "engagement_reward_v1"
      priority: 96
      cooldown_days: 14

  - id: course_completion_celebration
    description: "Celebrate course completions"
    when:
      all:
        - gte: { field: "completed_courses", value: 1 }
        - eq:  { field: "unsubscribed", value: false }
        - lt:  { field: "emails_sent_7d", value: 1 }
    action:
      template_id: "course_completion_v1"
      priority: 94
      cooldown_days: 7

  # --- AI-ASSISTED SUPPORT ---

  - id: learning_support_trigger
    description: "Provide learning support based on AI triggers"
    when:
      all:
        - contains_trigger: { field: "ai_email_triggers", trigger: "learning_support" }
        - contains_trigger: { field: "ai_email_triggers", message_type: "learning_support_offer" }
        - lt:  { field: "emails_sent_7d", value: 2 }
        - eq:  { field: "unsubscribed", value: false }
    action:
      template_id: "learning_support_v1"
      priority: 93
      cooldown_days: 3

  # --- SUBJECT-AREA NUDGES ---

  - id: help_pharmacology_general
    description: "Pharmacology help for any pharmacology subtopic"
    when:
      all:
        - contains_pattern: { field: "top_topics", pattern: "Pharmacology>*" }
        - lt:  { field: "emails_sent_7d", value: 2 }
        - eq:  { field: "unsubscribed", value: false }
        - gte: { field: "frequency_7d", value: 2 }
    action:
      template_id: "pharmacology_help_v1"
      priority: 92
      cooldown_days: 3

  - id: help_biology_general
    description: "Biology help for any biology subtopic"
    when:
      all:
        - contains_pattern: { field: "top_topics", pattern: "Biology>*" }
        - lt:  { field: "emails_sent_7d", value: 2 }
        - eq:  { field: "unsubscribed", value: false }
        - gte: { field: "frequency_7d", value: 2 }
    action:
      template_id: "biology_help_v1"
      priority: 90
      cooldown_days: 3

  - id: help_immunology_general
    description: "Immunology help for any immunology subtopic"
    when:
      all:
        - contains_pattern: { field: "top_topics", pattern: "Immunology>*" }
        - lt:  { field: "emails_sent_7d", value: 2 }
        - eq:  { field: "unsubscribed", value: false }
        - gte: { field: "frequency_7d", value: 2 }
    action:
      template_id: "immunology_help_v1"
      priority: 88
      cooldown_days: 3

  - id: help_history_general
    description: "History help for any history subtopic"
    when:
      all:
        - contains_pattern: { field: "top_topics", pattern: "History>*" }
        - lt:  { field: "emails_sent_7d", value: 2 }
        - eq:  { field: "unsubscribed", value: false }
        - gte: { field: "frequency_7d", value: 2 }
    action:
      template_id: "history_help_v1"
      priority: 85
      cooldown_days: 3

  # --- PERFORMANCE / WINBACK ---

  - id: test_performance_help
    description: "Help for users with low test performance"
    when:
      all:
        - gte: { field: "tests_7d", value: 100 }
        - lt:  { field: "test_accuracy", value: 0.5 }
        - eq:  { field: "unsubscribed", value: false }
    action:
      template_id: "test_improvement_v1"
      priority: 87
      cooldown_days: 5

  - id: winback_idle
    description: "Win back idle users"
    when:
      all:
        - gte: { field: "recency_days", value: 7 }
        - lte: { field: "recency_days", value: 30 }
        - eq:  { field: "unsubscribed", value: false }
    action:
      template_id: "winback_study_plan_v1"
      priority: 60
      cooldown_days: 7
